### ISSUE TITLE
runtimeError: freeze_support

### ISSUE THREAD

**Issue by hdr110** [alfem/telegram-downloader-bot#3]
Hello, my friend.
I'm using your script to download my files from telegram.
I did ALL you said before running the script but it fails after 'Downloader ready!' message, because of this error:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Python37\Lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "C:\Python37\Lib\multiprocessing\spawn.py", line 114, in _main
    prepare(preparation_data)
  File "C:\Python37\Lib\multiprocessing\spawn.py", line 225, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Python37\Lib\multiprocessing\spawn.py", line 277, in _fixup_main_from
_path
    run_name="__mp_main__")
  File "C:\Python37\Lib\runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "C:\Python37\Lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "C:\Python37\Lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
", line 56, in <module>
    manager = Manager()
  File "C:\Python37\Lib\multiprocessing\context.py", line 56, in Manager
    m.start()
  File "C:\Python37\Lib\multiprocessing\managers.py", line 543, in start
    self._process.start()
  File "C:\Python37\Lib\multiprocessing\process.py", line 112, in start
    self._popen = self._Popen(self)
  File "C:\Python37\Lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "C:\Python37\Lib\multiprocessing\popen_spawn_win32.py", line 46, in __ini
t__
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "C:\Python37\Lib\multiprocessing\spawn.py", line 143, in get_preparation_
data
    _check_not_importing_main()
  File "C:\Python37\Lib\multiprocessing\spawn.py", line 136, in _check_not_impor
ting_main
    is not going to be frozen to produce an executable.''')
RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.

-------------------------------------------------------------------------------
What should I do to solve this?
Should I use previous versions of these libraries? or some parts of this script is missing?
I'm using Windows 7 x64.
Thanks. A LOT.

**Comment by alfem** [comment]
I have tested it with python 2.7 and 3.5, and I can not reproduce those errors. 

Could you try to downgrade your Python version?

**Comment by alfem** [comment]
Anyway I moved main program to the typical "if __name__ == '__main__' construction. I do not now if that helps with your error.
